<?php
// Include patient session configuration FIRST
$root_path = dirname(dirname(dirname(__DIR__)));
require_once $root_path . '/config/session/patient_session.php';

// Check if user is logged in
if (!isset($_SESSION['patient_id'])) {
    header('Location: ../auth/patient_login.php');
    exit();
}

// Database connection
require_once $root_path . '/config/db.php';

$patient_id = $_SESSION['patient_id'];

try {
    // Get patient info
    $stmt = $conn->prepare("
        SELECT p.*, b.barangay_name
        FROM patients p
        LEFT JOIN barangay b ON p.barangay_id = b.barangay_id
        WHERE p.patient_id = ?
    ");
    $stmt->bind_param("i", $patient_id);
    $stmt->execute();
    $result = $stmt->get_result();
    $patient_info = $result->fetch_assoc();
    $stmt->close();

    // Get prescriptions with medications
    $stmt = $conn->prepare("
        SELECT p.*,
               CONCAT(e.first_name, ' ', e.last_name) as doctor_name,
               e.position,
               a.appointment_date, a.appointment_time,
               GROUP_CONCAT(
                   CONCAT(pm.medication_name, ' (', pm.dosage, 
                          CASE WHEN pm.frequency IS NOT NULL THEN CONCAT(', ', pm.frequency) ELSE '' END,
                          CASE WHEN pm.duration IS NOT NULL THEN CONCAT(', ', pm.duration) ELSE '' END, ')')
                   SEPARATOR '; '
               ) as medications_list,
               COUNT(pm.prescribed_medication_id) as medication_count
        FROM prescriptions p
        LEFT JOIN employees e ON p.prescribed_by_employee_id = e.employee_id
        LEFT JOIN appointments a ON p.appointment_id = a.appointment_id
        LEFT JOIN prescribed_medications pm ON p.prescription_id = pm.prescription_id
        WHERE p.patient_id = ?
        GROUP BY p.prescription_id
        ORDER BY p.prescription_date DESC
    ");
    $stmt->bind_param("i", $patient_id);
    $stmt->execute();
    $result = $stmt->get_result();
    $prescriptions = $result->fetch_all(MYSQLI_ASSOC);
    $stmt->close();

} catch (Exception $e) {
    die("Error retrieving prescription data: " . $e->getMessage());
}

// Set headers for file download
$filename = 'prescription_history_' . $patient_info['last_name'] . '_' . date('Y-m-d') . '.csv';
header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-cache, must-revalidate');

// Create file handle for output
$output = fopen('php://output', 'w');

// Add BOM for proper UTF-8 encoding in Excel
fputs($output, "\xEF\xBB\xBF");

// Write patient information header
fputcsv($output, ['PRESCRIPTION HISTORY REPORT']);
fputcsv($output, ['']);
fputcsv($output, ['Patient Name:', $patient_info['first_name'] . ' ' . $patient_info['middle_name'] . ' ' . $patient_info['last_name']]);
fputcsv($output, ['Date of Birth:', date('F j, Y', strtotime($patient_info['date_of_birth']))]);
fputcsv($output, ['Sex:', ucfirst($patient_info['sex'])]);
fputcsv($output, ['Address:', $patient_info['address'] . ', ' . ($patient_info['barangay_name'] ?? 'N/A')]);
fputcsv($output, ['Contact Number:', $patient_info['phone_number'] ?? 'N/A']);
fputcsv($output, ['Generated on:', date('F j, Y g:i A')]);
fputcsv($output, ['']);
fputcsv($output, ['']);

// Write CSV headers
fputcsv($output, [
    'Prescription ID',
    'Date Prescribed',
    'Time',
    'Prescribed By',
    'Doctor Position',
    'Number of Medications',
    'Medications List',
    'Status',
    'Appointment Date',
    'Remarks'
]);

// Write prescription data
if (!empty($prescriptions)) {
    foreach ($prescriptions as $prescription) {
        fputcsv($output, [
            $prescription['prescription_id'],
            date('F j, Y', strtotime($prescription['prescription_date'])),
            date('g:i A', strtotime($prescription['prescription_date'])),
            'Dr. ' . ($prescription['doctor_name'] ?? 'Unknown'),
            $prescription['position'] ?? 'N/A',
            $prescription['medication_count'],
            $prescription['medications_list'] ?? 'No medications',
            strtoupper($prescription['status']),
            $prescription['appointment_date'] ? date('F j, Y', strtotime($prescription['appointment_date'])) : 'N/A',
            $prescription['remarks'] ?? ''
        ]);
    }
} else {
    fputcsv($output, ['No prescriptions found', '', '', '', '', '', '', '', '', '']);
}

// Add footer
fputcsv($output, ['']);
fputcsv($output, ['']);
fputcsv($output, ['Total Prescriptions:', count($prescriptions)]);
fputcsv($output, ['Report generated by:', 'CHO Koronadal - Patient Portal']);
fputcsv($output, ['System:', 'Web-Based Healthcare Services Management System']);

fclose($output);
exit();
?>